# /*---------------------------------------------------------------------------*
#  Operating Systems I - CS4500 SEC001
#  Project 1  : System Calls and Processes
#  Composed By: Joseph Burns
#  Dated      : 12 September 2018
#  File Name  : Makefile 
# \*---------------------------------------------------------------------------*/
#
# Makes the code for the new system calls

obj-y := sys_helloworld.o sys_print_self.o sys_print_other.o sys_vma_stats.o sys_mem_status.o
